// Real-model backend for the R&D Council.
//
// Replaces the hardcoded template proposals with proposals generated by a model
// the user actually has configured in OpenClaw. Self-contained ESM (no TS / alias
// imports) so it can be imported from self-improvement-data.mjs without bundler
// surprises.
//
// Model selection priority:
//   1. process.env.OPENCLAW_COUNCIL_MODEL   (format "provider/model")
//   2. the agent's primary model from openclaw.json
//   3. DEFAULT_COUNCIL_MODEL literal
//
// Provider config is read from BOTH ~/.openclaw/openclaw.json (.models.providers)
// and ~/.openclaw/agents/main/agent/models.json (.providers), because providers
// such as `stepfun` only live in the former.
//
// Secrets (apiKey) are NEVER included in the prompt sent to the model.

import fs from "fs";
import os from "os";
import path from "path";

const OPENCLAW_HOME = process.env.OPENCLAW_HOME || path.join(os.homedir(), ".openclaw");
const OPENCLAW_CONFIG_PATH = path.join(OPENCLAW_HOME, "openclaw.json");
const MODELS_JSON_PATH = path.join(OPENCLAW_HOME, "agents", "main", "agent", "models.json");

export const DEFAULT_COUNCIL_MODEL = "stepfun/step-3.7-flash";
const DEFAULT_TIMEOUT_MS = 90_000;
const VALID_LENSES = new Set(["efficiency", "infrastructure", "pattern", "external"]);
const VALID_CONFIDENCE = new Set(["low", "medium", "high"]);

function readJsonSafe(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch {
    return null;
  }
}

export function parseModelRef(ref) {
  const value = String(ref || "").trim();
  const slash = value.indexOf("/");
  if (slash === -1) return { providerId: value, modelId: value };
  return { providerId: value.slice(0, slash), modelId: value.slice(slash + 1) };
}

// Merge providers from both config files. models.json wins on key collision only
// for fields it actually defines; openclaw.json provides providers absent there.
function loadAllProviders() {
  const out = {};
  const oc = readJsonSafe(OPENCLAW_CONFIG_PATH);
  const ocProviders = oc?.models?.providers;
  if (ocProviders && typeof ocProviders === "object") {
    for (const [id, cfg] of Object.entries(ocProviders)) out[id] = cfg;
  }
  const mj = readJsonSafe(MODELS_JSON_PATH);
  const mjProviders = mj?.providers;
  if (mjProviders && typeof mjProviders === "object") {
    for (const [id, cfg] of Object.entries(mjProviders)) {
      out[id] = { ...(out[id] || {}), ...cfg };
    }
  }
  return out;
}

export function loadProviderConfig(providerId) {
  const providers = loadAllProviders();
  if (providers[providerId]) return providers[providerId];
  const target = String(providerId || "").toLowerCase();
  for (const [key, value] of Object.entries(providers)) {
    if (key.toLowerCase() === target) return value;
  }
  return null;
}

// Resolve which provider/model the council should use.
export function resolveCouncilModelRef() {
  const envRef = (process.env.OPENCLAW_COUNCIL_MODEL || "").trim();
  if (envRef) return envRef;

  const oc = readJsonSafe(OPENCLAW_CONFIG_PATH);
  // Common shapes: agents.main.model, agents.defaults.model, models.mode primary, etc.
  const candidates = [
    oc?.agents?.main?.model,
    oc?.agents?.defaults?.model,
    oc?.agent?.model,
    oc?.model,
  ];
  for (const c of candidates) {
    if (typeof c === "string" && c.includes("/")) return c;
    if (c && typeof c === "object" && typeof c.primary === "string" && c.primary.includes("/")) {
      return c.primary;
    }
  }
  return DEFAULT_COUNCIL_MODEL;
}

// ----- usage profile (real signal, no secrets) -----------------------------

function platformFromKey(key) {
  // keys look like: agent:main:discord:channel:123  /  agent:main:feishu:group:xxx
  const parts = String(key).split(":");
  const idx = parts.indexOf("main");
  const candidate = idx >= 0 ? parts[idx + 1] : parts[2];
  return candidate || "unknown";
}

// sessionsData from sessions.json is a map of sessionKey -> metadata.
export function buildUsageProfile(sessionsData) {
  const entries =
    sessionsData && typeof sessionsData === "object" && !Array.isArray(sessionsData)
      ? Object.entries(sessionsData)
      : [];

  const platforms = {};
  const models = {};
  const chatTypes = {};
  let total = 0;
  let mostRecent = null;

  for (const [key, meta] of entries) {
    if (!meta || typeof meta !== "object") continue;
    total += 1;
    const platform = meta.channel || platformFromKey(key);
    platforms[platform] = (platforms[platform] || 0) + 1;
    const model = meta.model || meta.modelProvider || "unknown";
    models[model] = (models[model] || 0) + 1;
    const chatType = meta.chatType || "unknown";
    chatTypes[chatType] = (chatTypes[chatType] || 0) + 1;
    const updated = meta.updatedAt || meta.updated_at;
    if (updated && (!mostRecent || String(updated) > mostRecent)) mostRecent = String(updated);
  }

  // configured providers/models — ids only, NO apiKeys
  const providers = loadAllProviders();
  const configuredModels = [];
  for (const [pid, cfg] of Object.entries(providers)) {
    const ms = Array.isArray(cfg?.models) ? cfg.models : [];
    for (const m of ms) {
      const id = typeof m === "string" ? m : m?.id || m?.name;
      if (id) configuredModels.push(`${pid}/${id} (api=${cfg?.api || "openai-completions"})`);
    }
  }

  return {
    total_sessions: total,
    by_platform: platforms,
    by_model: models,
    by_chat_type: chatTypes,
    most_recent_activity: mostRecent,
    configured_models: configuredModels,
  };
}

// ----- prompt --------------------------------------------------------------

const COUNCIL_SYSTEM_PROMPT = `You are the R&D Council for an operator running multiple OpenClaw AI agents across chat platforms (Discord, Feishu, WhatsApp, Telegram, dashboard, etc.).

Your job: from the operator's real usage profile, surface concrete, high-leverage improvement proposals. Operate in PROACTIVE mode across four lenses:
- efficiency: what could be automated / what is slow / what repeats
- infrastructure: what foundational system would unlock multiple things
- pattern: what keeps getting half-built without finishing
- external: what the market/ecosystem is rewarding right now

For EACH proposal, run a short internal debate among these roles before deciding:
- Devil's Advocate (why this is a distraction now)
- Resource Check (effort + skills needed)
- Impact Estimator (measurable outcome if built)
- Timing Analyst (is now the right time)

Confidence levels: low (needs research), medium (clear concept, needs validation), high (strong evidence, ready to act).

Return STRICT JSON ONLY (no markdown, no prose) of this exact shape:
{
  "items": [
    {
      "title": "short imperative title",
      "summary": "1-2 sentence description grounded in the usage profile",
      "lens": "efficiency | infrastructure | pattern | external",
      "confidence": "low | medium | high",
      "debate_summary": ["3-5 short bullet strings capturing the debate"],
      "key_disagreements": [
        {"model": "devil-advocate", "concern": "...", "resolution": "..."}
      ],
      "recommendation": "the council's concrete recommended next step",
      "passing_reasoning": "why this proposal passes to the operator"
    }
  ]
}

Rules: 3 to 5 items, each from a DIFFERENT lens where possible. Ground every proposal in the actual platforms/models/usage given. Be specific to OpenClaw operations, not generic. Output JSON only.`;

function buildUserPrompt(profile, max) {
  return [
    `Generate up to ${max} R&D Council proposals from this operator usage profile.`,
    "",
    "USAGE PROFILE (JSON):",
    JSON.stringify(profile, null, 2),
    "",
    "Remember: STRICT JSON only, matching the schema in the system prompt.",
  ].join("\n");
}

// ----- model call ----------------------------------------------------------

function pickAuthHeaders(cfg, apiKey) {
  const authHeader = cfg?.authHeader;
  if (typeof authHeader === "string" && authHeader.trim()) return { [authHeader.trim()]: apiKey };
  if (authHeader === false) return { "x-api-key": apiKey };
  if (cfg?.api === "anthropic-messages") {
    return { "x-api-key": apiKey, Authorization: `Bearer ${apiKey}` };
  }
  return { Authorization: `Bearer ${apiKey}` };
}

// Optional proxy support. Node's global fetch ignores HTTP(S)_PROXY env vars.
// Under Clash TUN mode (fake-ip) plain fetch works transparently, so this is a
// no-op unless an HTTP proxy is configured AND `undici` happens to be installed.
// Resolves to { fetch, dispatcher } (undici's OWN fetch + ProxyAgent) or null.
// Note: a standalone undici's ProxyAgent is NOT compatible with Node's built-in
// global fetch (version-mismatched dispatcher → "invalid onRequestStart method"),
// so when proxying we must use undici's own fetch, not the global one. Cached;
// never throws.
let _proxyClientPromise;
async function getProxyClient() {
  if (_proxyClientPromise !== undefined) return _proxyClientPromise;
  _proxyClientPromise = (async () => {
    const proxyUrl = (
      process.env.HTTPS_PROXY ||
      process.env.https_proxy ||
      process.env.HTTP_PROXY ||
      process.env.http_proxy ||
      ""
    ).trim();
    // undici ProxyAgent only supports HTTP CONNECT proxies, not socks.
    if (!proxyUrl || /^socks/i.test(proxyUrl)) return null;
    try {
      // Opaque specifier + ignore directives so the bundler does not try to
      // resolve `undici` at build time (it is an optional, runtime-only dep).
      const specifier = "undici";
      const undici = await import(/* webpackIgnore: true */ /* turbopackIgnore: true */ specifier);
      if (undici?.ProxyAgent && undici?.fetch) {
        return { fetch: undici.fetch, dispatcher: new undici.ProxyAgent(proxyUrl) };
      }
    } catch {
      // undici not installed — fall back to plain fetch (TUN mode covers it).
    }
    return null;
  })();
  return _proxyClientPromise;
}

async function fetchWithTimeout(url, init, timeoutMs) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  const proxy = await getProxyClient();
  try {
    if (proxy) {
      return await proxy.fetch(url, { ...init, signal: controller.signal, dispatcher: proxy.dispatcher });
    }
    return await fetch(url, { ...init, signal: controller.signal, cache: "no-store" });
  } finally {
    clearTimeout(timer);
  }
}

// Returns { ok, text, error } where text is the raw model output string.
async function callModel({ cfg, modelId, system, user, maxTokens = 4000, timeoutMs = DEFAULT_TIMEOUT_MS }) {
  const baseUrl = String(cfg?.baseUrl || "").replace(/\/+$/, "");
  const apiKey = cfg?.apiKey;
  if (!baseUrl || !apiKey) return { ok: false, error: "Provider missing baseUrl or apiKey" };
  const api = cfg?.api || "openai-completions";
  const headers = {
    "content-type": "application/json",
    ...(cfg?.headers || {}),
    ...pickAuthHeaders(cfg, apiKey),
  };

  try {
    if (api === "anthropic-messages") {
      if (!headers["anthropic-version"]) headers["anthropic-version"] = "2023-06-01";
      const url = `${baseUrl}/v1/messages`;
      const body = {
        model: modelId,
        max_tokens: maxTokens,
        system,
        messages: [{ role: "user", content: user }],
        temperature: 0.6,
      };
      const resp = await fetchWithTimeout(url, { method: "POST", headers, body: JSON.stringify(body) }, timeoutMs);
      if (!resp.ok) return { ok: false, error: await describeHttpError(resp) };
      const json = await resp.json();
      const text = Array.isArray(json?.content)
        ? json.content.filter((p) => p?.type === "text").map((p) => p.text).join("")
        : "";
      return { ok: true, text };
    }

    // openai-completions / ollama / openai-responses-ish all accept chat/completions here
    const url = `${baseUrl}/chat/completions`;
    const body = {
      model: modelId,
      messages: [
        { role: "system", content: system },
        { role: "user", content: user },
      ],
      max_tokens: maxTokens,
      temperature: 0.6,
    };
    const resp = await fetchWithTimeout(url, { method: "POST", headers, body: JSON.stringify(body) }, timeoutMs);
    if (!resp.ok) return { ok: false, error: await describeHttpError(resp) };
    const json = await resp.json();
    const text = json?.choices?.[0]?.message?.content ?? "";
    return { ok: true, text: String(text) };
  } catch (err) {
    const isTimeout = err?.name === "AbortError";
    return { ok: false, error: isTimeout ? `Model request timed out after ${timeoutMs}ms` : (err?.message || "Network error") };
  }
}

async function describeHttpError(resp) {
  let payload = null;
  try {
    payload = await resp.json();
  } catch {}
  const msg = payload?.error?.message || payload?.message || payload?.error;
  return `HTTP ${resp.status}${typeof msg === "string" && msg.trim() ? `: ${msg.trim()}` : ""}`;
}

// Extract the first balanced JSON object/array from possibly-fenced model output.
export function extractJson(text) {
  const raw = String(text || "");
  for (let i = 0; i < raw.length; i++) {
    const ch = raw[i];
    if (ch !== "{" && ch !== "[") continue;
    const open = ch;
    const close = ch === "{" ? "}" : "]";
    let depth = 0;
    let inString = false;
    let escaped = false;
    for (let j = i; j < raw.length; j++) {
      const c = raw[j];
      if (inString) {
        if (escaped) escaped = false;
        else if (c === "\\") escaped = true;
        else if (c === '"') inString = false;
        continue;
      }
      if (c === '"') inString = true;
      else if (c === open) depth++;
      else if (c === close) {
        depth--;
        if (depth === 0) {
          const candidate = raw.slice(i, j + 1);
          try {
            return JSON.parse(candidate);
          } catch {
            break;
          }
        }
      }
    }
  }
  return null;
}

function sanitizeProposal(raw) {
  if (!raw || typeof raw !== "object") return null;
  const title = typeof raw.title === "string" ? raw.title.trim() : "";
  if (!title) return null;
  const lens = VALID_LENSES.has(raw.lens) ? raw.lens : "pattern";
  const confidence = VALID_CONFIDENCE.has(raw.confidence) ? raw.confidence : "medium";
  const debate = Array.isArray(raw.debate_summary)
    ? raw.debate_summary.map((s) => String(s).trim()).filter(Boolean).slice(0, 8)
    : [];
  const disagreements = Array.isArray(raw.key_disagreements)
    ? raw.key_disagreements
        .map((d) => ({
          model: String(d?.model || "devil-advocate").trim() || "devil-advocate",
          concern: String(d?.concern || "").trim(),
          resolution: String(d?.resolution || "").trim(),
        }))
        .filter((d) => d.concern || d.resolution)
        .slice(0, 6)
    : [];
  return {
    title,
    summary: typeof raw.summary === "string" && raw.summary.trim() ? raw.summary.trim() : title,
    lens,
    confidence,
    debate_summary: debate,
    key_disagreements: disagreements,
    recommendation: typeof raw.recommendation === "string" ? raw.recommendation.trim() : "",
    passing_reasoning: typeof raw.passing_reasoning === "string" ? raw.passing_reasoning.trim() : "",
  };
}

// Main entry: returns { ok, model, proposals, reason }.
export async function generateCouncilProposals(sessionsData, opts = {}) {
  const max = Math.max(1, Math.min(6, opts.max ?? 5));
  if (String(process.env.OPENCLAW_COUNCIL_DISABLE_MODEL).toLowerCase() === "true") {
    return { ok: false, model: null, proposals: [], reason: "Model generation disabled via OPENCLAW_COUNCIL_DISABLE_MODEL" };
  }

  const modelRef = resolveCouncilModelRef();
  const { providerId, modelId } = parseModelRef(modelRef);
  const cfg = loadProviderConfig(providerId);
  if (!cfg) return { ok: false, model: modelRef, proposals: [], reason: `Provider "${providerId}" not found in OpenClaw config` };
  if (!cfg.apiKey) return { ok: false, model: modelRef, proposals: [], reason: `Provider "${providerId}" has no apiKey configured` };

  const profile = buildUsageProfile(sessionsData);
  const result = await callModel({
    cfg,
    modelId,
    system: COUNCIL_SYSTEM_PROMPT,
    user: buildUserPrompt(profile, max),
    timeoutMs: opts.timeoutMs ?? DEFAULT_TIMEOUT_MS,
  });
  if (!result.ok) return { ok: false, model: modelRef, proposals: [], reason: result.error, profile };

  const parsed = extractJson(result.text);
  const rawItems = Array.isArray(parsed) ? parsed : Array.isArray(parsed?.items) ? parsed.items : [];
  const proposals = rawItems.map(sanitizeProposal).filter(Boolean).slice(0, max);
  if (proposals.length === 0) {
    return { ok: false, model: modelRef, proposals: [], reason: "Model returned no parseable proposals", profile };
  }
  return { ok: true, model: modelRef, proposals, reason: null, profile };
}
